language: java
# chnages what code runs remotely on the server
script: mvn test -B

# sets the operating systems of VM
os:
  - linux
  - osx

  jdk: oraclejdk8

  branches:
    only:
      - master

  deploy:
    provider: heroku:git
    api_key:
      secure:

